from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='main'),
    path('men', views.men, name='men'),
    path('women', views.women, name='women'),
    path('fornothing', views.fornothing, name='fornothing'),
    path('all', views.all, name='all'),
    path('handful', views.m1, name='m1'),
    path('glass', views.m2, name='m2'),
    path('baloon', views.m3, name='m3'),
    path('bag', views.m4, name='m4'),
    path('suitcase', views.m5, name='m5'),
    path('cistern', views.m6, name='m6'),
    path('truck', views.m7, name='m7'),
    path('plane', views.m8, name='m8'),
    path('tanker', views.m9, name='m9'),
    path('pipeline', views.m10, name='m10'),
    path('pan', views.w1, name='w1'),
    path('handbag', views.w2, name='w2'),
    path('wineglass', views.w3, name='w3'),
    path('trolley', views.w4, name='w4'),
    path('bottle', views.w5, name='w5'),
    path('justnothing', views.w6, name='w6'),
    path('capsule', views.w7, name='w7'),
    path('tube', views.w8, name='w8'),
    path('bigbox', views.w9, name='w9'),
    path('smallbox', views.w10, name='w10'),
    path('buybuybuy', views.buybuybuy, name='buybuybuy'),
    path('login', views.user_login, name='login'),
    path('logout', views.user_logout, name='logout'),
    path('registration', views.register, name='registration'),
    path('payment', views.pay, name='pay'),
]